name = "loja"
type = "module"
main = "src/index.js"
compatibility_date = "2025-08-30"
account_id = "616fe3162444437af25f52d02b28e9f7"

[workers]
loja = { main = "src/worker-loja.js" }
admin = { main = "src/worker-admin.js" }
