name = "seu-worker" # Substitua por um nome único para o Worker
main = "index.js" # Define index.js como o ponto de entrada
compatibility_date = "2025-08-30"
workers_dev = true
account_id = "SEU_ACCOUNT_ID" # Substitua pelo seu Cloudflare Account ID

# Desativa cache (opcional, para evitar problemas anteriores)
[triggers]
routes = ["loja.senhormaromba.com.br/*"]

# Configurações adicionais (se necessário)
[vars]
# Adicione variáveis de ambiente, se necessário
