name = "loja-senhormaromba"
compatibility_date = "2025-08-30"
account_id = "616fe3162444437af25f52d02b28e9f7"
main = "worker-loja/render.js"
workers_dev = true

# Se tiver CSS, imagens, fontes, etc., declare a pasta de assets
[assets]
directory = "./worker-loja/assets"
